name: CI

on:
  push:
    branches:
      - main
      - master
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      valkey:
        image: valkey/valkey:8.0
        ports:
          - 6379:6379
        options: >-
          --health-cmd "valkey-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Wait for Valkey
        run: |
          for i in {1..30}; do
            if python3 - <<'PY'
import socket
with socket.socket() as sock:
    sock.settimeout(1)
    sock.connect(("127.0.0.1", 6379))
PY
            then
              echo "Valkey is ready"
              exit 0
            fi
            sleep 1
          done
          echo "Valkey did not become ready in time" >&2
          exit 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: node/package-lock.json

      - name: Install Node dependencies
        run: npm ci
        working-directory: node

      - name: Run Node unit tests
        run: npm test
        working-directory: node

      - name: Run Node example
        run: npm run example
        working-directory: node

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: python

      - name: Run Python unit tests
        run: pytest
        working-directory: python

      - name: Run Python example
        run: python main.py
        working-directory: python
